WeatherApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;
using ServiceContracts.Models;
using System.Linq;

namespace WeatherApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IWeatherService _cityService;

        public HomeController(IWeatherService cityService)
        {
            _cityService = cityService;
        }

        [Route("/")]
        public IActionResult Index()
        {
            List<CityWeather> cityWeatherList = _cityService.GetWeatherDetails();
            return View(cityWeatherList);
        }

        [Route("weather/{cityCode}")]
        public IActionResult Weather(string cityCode)
        {
            CityWeather cityWeather = _cityService.GetWeatherByCityCode(cityCode);
            if (cityWeather == null)
                return NotFound($"City with code '{cityCode}' is not found");
            return View(cityWeather);
        }
    }
}

WeatherApp/ViewComponents/WeatherListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts.Models;

namespace WeatherApp.ViewComponents
{
    public class WeatherListViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(List<CityWeather> model)
        {
            return View(model);
        }
    }
}

WeatherApp/Views/Home/Index.cshtml
@model IEnumerable<CityWeather>

<!DOCTYPE html>
<head>
    <title>Weather</title>
    <meta charset="utf-8"/>
    <link href="~/stylesheet.css" rel="stylesheet" />
</head>
<body>
    @await Component.InvokeAsync("WeatherList", Model)
</body>

WeatherApp/Views/Home/Weather.cshtml
@model CityWeather

<!DOCTYPE html>
<head>
    <title>@Model.CityName City Weather</title>
    <meta charset="utf-8"/>
    <link href="~/stylesheet.css" rel="stylesheet" />
</head>
<body>
    <div class="w-30 margin-auto cursor-pointer">
        <div class="box w-30 margin-auto">
            <div class="inline-block w-50">
                <h2>@Model.CityName</h2>
                <h4 class="text-dark-grey">@Model.GetDayMonthYear()</h4>
                <h4 class="text-dark-grey">@Model.GetTime()</h4>
            </div>
            <div class="border-left inline-block padding-left-45">
                <h2 class="text-dark-grey">@Model.TemperatureFahrenheit <sup><sup>o</sup>F</sup></h2>
                <br/><br/>
            </div>
        </div>
        <div class="margin-auto text-center">
            <a href="/">Back To The Home Page</a>
        </div>
    </div>
</body>

WeatherApp/Views/Shared/Components/WeatherList/Default.cshtml
@model IEnumerable<CityWeather>

@{
    string GetColorByTemperature(int temperature)
    {
        if (temperature < 44)
            return "blue-back";
        else if (temperature > 74)
            return "orange-back";
        else
            return "green-back";
    }
}

@foreach (var item in Model)
{
    <div class="w-30 box @GetColorByTemperature(item.TemperatureFahrenheit) margin-left cursor-pointer">
        <div class="inline-block w-50">
            <h2>@item.CityName</h2>
            <h4 class=" text-dark-grey">@item.GetTime()</h4>
            <div class="margin-top">
                <a href="weather/@item.CityUniqueCode">Details</a>
            </div>
            
        </div>
        <div class="border-left inline-block padding-left-45">
             <h2 class="text-dark-grey">@item.TemperatureFahrenheit <sup><sup>o</sup>F</sup><h2>
             <br/><br/>
        </div>
    </div>
}

WeatherApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/stylesheet.css" rel="stylesheet" />
</head>
<body>
    <div class="page-content">
        <h1>Weather</h1>
        <div class="margin-top-200 flex-borderless">
            @RenderBody()
        </div>
    </div>
</body>
</html>

WeatherApp/Views/Shared/_WeatherListPartial.cshtml
@model IEnumerable<CityWeather>

@{
    string GetColorByTemperature(int temperature)
    {
        if (temperature < 44)
            return "blue-back";
        else if (temperature > 74)
            return "orange-back";
        else
            return "green-back";
    }
}

@foreach (var item in Model)
{
    <div class="w-30 box @GetColorByTemperature(item.TemperatureFahrenheit) margin-left cursor-pointer">
        <div class="inline-block w-50">
            <h2>@item.CityName</h2>
            <h4 class=" text-dark-grey">@item.GetTime()</h4>
            <div class="margin-top">
                <a href="weather/@item.CityUniqueCode">Details</a>
            </div>
            
        </div>
        <div class="border-left inline-block padding-left-45">
             <h2 class="text-dark-grey">@item.TemperatureFahrenheit <sup><sup>o</sup>F</sup><h2>
             <br/><br/>
        </div>
    </div>
}